# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from protopb.robot_skill_api import robot_operator_api_pb2 as robot__skill__api_dot_robot__operator__api__pb2


class RobotOperatorServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SwitchHi = channel.unary_unary(
        '/robotSkillApi.RobotOperatorService/SwitchHi',
        request_serializer=robot__skill__api_dot_robot__operator__api__pb2.SwitchRequest.SerializeToString,
        response_deserializer=robot__skill__api_dot_robot__operator__api__pb2.OperatorBaseResponse.FromString,
        )
    self.UpdateConfidenceIndex = channel.unary_unary(
        '/robotSkillApi.RobotOperatorService/UpdateConfidenceIndex',
        request_serializer=robot__skill__api_dot_robot__operator__api__pb2.ConfidenceRequest.SerializeToString,
        response_deserializer=robot__skill__api_dot_robot__operator__api__pb2.OperatorBaseResponse.FromString,
        )
    self.UpdateChichat = channel.unary_unary(
        '/robotSkillApi.RobotOperatorService/UpdateChichat',
        request_serializer=robot__skill__api_dot_robot__operator__api__pb2.ChichatRequest.SerializeToString,
        response_deserializer=robot__skill__api_dot_robot__operator__api__pb2.OperatorBaseResponse.FromString,
        )
    self.SendFR = channel.unary_unary(
        '/robotSkillApi.RobotOperatorService/SendFR',
        request_serializer=robot__skill__api_dot_robot__operator__api__pb2.FaceRecognitionRequest.SerializeToString,
        response_deserializer=robot__skill__api_dot_robot__operator__api__pb2.OperatorBaseResponse.FromString,
        )


class RobotOperatorServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SwitchHi(self, request, context):
    """切换人工
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateConfidenceIndex(self, request, context):
    """更新信心值
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateChichat(self, request, context):
    """更改闲聊设置
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendFR(self, request, context):
    """发送识别出的人脸信息
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RobotOperatorServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SwitchHi': grpc.unary_unary_rpc_method_handler(
          servicer.SwitchHi,
          request_deserializer=robot__skill__api_dot_robot__operator__api__pb2.SwitchRequest.FromString,
          response_serializer=robot__skill__api_dot_robot__operator__api__pb2.OperatorBaseResponse.SerializeToString,
      ),
      'UpdateConfidenceIndex': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateConfidenceIndex,
          request_deserializer=robot__skill__api_dot_robot__operator__api__pb2.ConfidenceRequest.FromString,
          response_serializer=robot__skill__api_dot_robot__operator__api__pb2.OperatorBaseResponse.SerializeToString,
      ),
      'UpdateChichat': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateChichat,
          request_deserializer=robot__skill__api_dot_robot__operator__api__pb2.ChichatRequest.FromString,
          response_serializer=robot__skill__api_dot_robot__operator__api__pb2.OperatorBaseResponse.SerializeToString,
      ),
      'SendFR': grpc.unary_unary_rpc_method_handler(
          servicer.SendFR,
          request_deserializer=robot__skill__api_dot_robot__operator__api__pb2.FaceRecognitionRequest.FromString,
          response_serializer=robot__skill__api_dot_robot__operator__api__pb2.OperatorBaseResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'robotSkillApi.RobotOperatorService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
