# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: robot-skill-api/robot-tts-api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from protopb.common import common_pb2 as common_dot_common__pb2
from protopb.common import qa_pb2 as common_dot_qa__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='robot-skill-api/robot-tts-api.proto',
  package='robotSkillApi',
  syntax='proto3',
  serialized_options=_b('Z<cloudminds.com/harix/harix-skill-robot/proto/robot-skill-api'),
  serialized_pb=_b('\n#robot-skill-api/robot-tts-api.proto\x12\rrobotSkillApi\x1a\x1cgoogle/protobuf/struct.proto\x1a\x13\x63ommon/common.proto\x1a\x0f\x63ommon/qa.proto\"_\n\x0cSpeakRequest\x12.\n\x0f\x63ommon_req_info\x18\x01 \x01(\x0b\x32\x15.common.CommonReqInfo\x12\x1f\n\x03tts\x18\x02 \x03(\x0b\x32\x12.robotSkillApi.Tts\"\xe9\x01\n\x03Tts\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0c\n\x04lang\x18\x02 \x01(\t\x12,\n\x06\x61\x63tion\x18\x03 \x01(\x0b\x32\x1c.robotSkillApi.Tts.TtsAction\x1a\x97\x01\n\tTtsAction\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x36\n\x05param\x18\x02 \x03(\x0b\x32\'.robotSkillApi.Tts.TtsAction.ParamEntry\x1a\x44\n\nParamEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.google.protobuf.Value:\x02\x38\x01\"O\n\rSpeakResponse\x12.\n\x0f\x63ommon_rsp_info\x18\x01 \x01(\x0b\x32\x15.common.CommonRspInfo\x12\x0e\n\x06result\x18\x02 \x01(\t2\x94\x01\n\x0fRobotTtsService\x12\x44\n\x05Speak\x12\x1b.robotSkillApi.SpeakRequest\x1a\x1c.robotSkillApi.SpeakResponse\"\x00\x12;\n\x06SendQa\x12\x11.common.SwMessage\x1a\x1c.robotSkillApi.SpeakResponse\"\x00\x42>Z<cloudminds.com/harix/harix-skill-robot/proto/robot-skill-apib\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,common_dot_common__pb2.DESCRIPTOR,common_dot_qa__pb2.DESCRIPTOR,])




_SPEAKREQUEST = _descriptor.Descriptor(
  name='SpeakRequest',
  full_name='robotSkillApi.SpeakRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='common_req_info', full_name='robotSkillApi.SpeakRequest.common_req_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tts', full_name='robotSkillApi.SpeakRequest.tts', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=217,
)


_TTS_TTSACTION_PARAMENTRY = _descriptor.Descriptor(
  name='ParamEntry',
  full_name='robotSkillApi.Tts.TtsAction.ParamEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='robotSkillApi.Tts.TtsAction.ParamEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='robotSkillApi.Tts.TtsAction.ParamEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=385,
  serialized_end=453,
)

_TTS_TTSACTION = _descriptor.Descriptor(
  name='TtsAction',
  full_name='robotSkillApi.Tts.TtsAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='robotSkillApi.Tts.TtsAction.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='param', full_name='robotSkillApi.Tts.TtsAction.param', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_TTS_TTSACTION_PARAMENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=302,
  serialized_end=453,
)

_TTS = _descriptor.Descriptor(
  name='Tts',
  full_name='robotSkillApi.Tts',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='robotSkillApi.Tts.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lang', full_name='robotSkillApi.Tts.lang', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action', full_name='robotSkillApi.Tts.action', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_TTS_TTSACTION, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=220,
  serialized_end=453,
)


_SPEAKRESPONSE = _descriptor.Descriptor(
  name='SpeakResponse',
  full_name='robotSkillApi.SpeakResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='common_rsp_info', full_name='robotSkillApi.SpeakResponse.common_rsp_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result', full_name='robotSkillApi.SpeakResponse.result', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=455,
  serialized_end=534,
)

_SPEAKREQUEST.fields_by_name['common_req_info'].message_type = common_dot_common__pb2._COMMONREQINFO
_SPEAKREQUEST.fields_by_name['tts'].message_type = _TTS
_TTS_TTSACTION_PARAMENTRY.fields_by_name['value'].message_type = google_dot_protobuf_dot_struct__pb2._VALUE
_TTS_TTSACTION_PARAMENTRY.containing_type = _TTS_TTSACTION
_TTS_TTSACTION.fields_by_name['param'].message_type = _TTS_TTSACTION_PARAMENTRY
_TTS_TTSACTION.containing_type = _TTS
_TTS.fields_by_name['action'].message_type = _TTS_TTSACTION
_SPEAKRESPONSE.fields_by_name['common_rsp_info'].message_type = common_dot_common__pb2._COMMONRSPINFO
DESCRIPTOR.message_types_by_name['SpeakRequest'] = _SPEAKREQUEST
DESCRIPTOR.message_types_by_name['Tts'] = _TTS
DESCRIPTOR.message_types_by_name['SpeakResponse'] = _SPEAKRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SpeakRequest = _reflection.GeneratedProtocolMessageType('SpeakRequest', (_message.Message,), {
  'DESCRIPTOR' : _SPEAKREQUEST,
  '__module__' : 'robot_skill_api.robot_tts_api_pb2'
  # @@protoc_insertion_point(class_scope:robotSkillApi.SpeakRequest)
  })
_sym_db.RegisterMessage(SpeakRequest)

Tts = _reflection.GeneratedProtocolMessageType('Tts', (_message.Message,), {

  'TtsAction' : _reflection.GeneratedProtocolMessageType('TtsAction', (_message.Message,), {

    'ParamEntry' : _reflection.GeneratedProtocolMessageType('ParamEntry', (_message.Message,), {
      'DESCRIPTOR' : _TTS_TTSACTION_PARAMENTRY,
      '__module__' : 'robot_skill_api.robot_tts_api_pb2'
      # @@protoc_insertion_point(class_scope:robotSkillApi.Tts.TtsAction.ParamEntry)
      })
    ,
    'DESCRIPTOR' : _TTS_TTSACTION,
    '__module__' : 'robot_skill_api.robot_tts_api_pb2'
    # @@protoc_insertion_point(class_scope:robotSkillApi.Tts.TtsAction)
    })
  ,
  'DESCRIPTOR' : _TTS,
  '__module__' : 'robot_skill_api.robot_tts_api_pb2'
  # @@protoc_insertion_point(class_scope:robotSkillApi.Tts)
  })
_sym_db.RegisterMessage(Tts)
_sym_db.RegisterMessage(Tts.TtsAction)
_sym_db.RegisterMessage(Tts.TtsAction.ParamEntry)

SpeakResponse = _reflection.GeneratedProtocolMessageType('SpeakResponse', (_message.Message,), {
  'DESCRIPTOR' : _SPEAKRESPONSE,
  '__module__' : 'robot_skill_api.robot_tts_api_pb2'
  # @@protoc_insertion_point(class_scope:robotSkillApi.SpeakResponse)
  })
_sym_db.RegisterMessage(SpeakResponse)


DESCRIPTOR._options = None
_TTS_TTSACTION_PARAMENTRY._options = None

_ROBOTTTSSERVICE = _descriptor.ServiceDescriptor(
  name='RobotTtsService',
  full_name='robotSkillApi.RobotTtsService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=537,
  serialized_end=685,
  methods=[
  _descriptor.MethodDescriptor(
    name='Speak',
    full_name='robotSkillApi.RobotTtsService.Speak',
    index=0,
    containing_service=None,
    input_type=_SPEAKREQUEST,
    output_type=_SPEAKRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendQa',
    full_name='robotSkillApi.RobotTtsService.SendQa',
    index=1,
    containing_service=None,
    input_type=common_dot_qa__pb2._SWMESSAGE,
    output_type=_SPEAKRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ROBOTTTSSERVICE)

DESCRIPTOR.services_by_name['RobotTtsService'] = _ROBOTTTSSERVICE

# @@protoc_insertion_point(module_scope)
