# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: robot-skill-api/robot-operator-api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protopb.common import common_pb2 as common_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='robot-skill-api/robot-operator-api.proto',
  package='robotSkillApi',
  syntax='proto3',
  serialized_options=_b('Z<cloudminds.com/harix/harix-skill-robot/proto/robot-skill-api'),
  serialized_pb=_b('\n(robot-skill-api/robot-operator-api.proto\x12\rrobotSkillApi\x1a\x13\x63ommon/common.proto\"i\n\rSwitchRequest\x12.\n\x0f\x63ommon_req_info\x18\x01 \x01(\x0b\x32\x15.common.CommonReqInfo\x12\x18\n\x10\x63onfidence_index\x18\x02 \x01(\x05\x12\x0e\n\x06reason\x18\x03 \x01(\t\"]\n\x11\x43onfidenceRequest\x12.\n\x0f\x63ommon_req_info\x18\x01 \x01(\x0b\x32\x15.common.CommonReqInfo\x12\x18\n\x10\x63onfidence_index\x18\x02 \x01(\x05\"V\n\x14OperatorBaseResponse\x12.\n\x0f\x63ommon_rsp_info\x18\x01 \x01(\x0b\x32\x15.common.CommonRspInfo\x12\x0e\n\x06result\x18\x02 \x01(\t\"Q\n\x0e\x43hichatRequest\x12.\n\x0f\x63ommon_req_info\x18\x01 \x01(\x0b\x32\x15.common.CommonReqInfo\x12\x0f\n\x07\x63hichat\x18\x02 \x01(\t\"V\n\x16\x46\x61\x63\x65RecognitionRequest\x12.\n\x0f\x63ommon_req_info\x18\x01 \x01(\x0b\x32\x15.common.CommonReqInfo\x12\x0c\n\x04\x62ody\x18\x02 \x01(\t2\xf8\x02\n\x14RobotOperatorService\x12O\n\x08SwitchHi\x12\x1c.robotSkillApi.SwitchRequest\x1a#.robotSkillApi.OperatorBaseResponse\"\x00\x12`\n\x15UpdateConfidenceIndex\x12 .robotSkillApi.ConfidenceRequest\x1a#.robotSkillApi.OperatorBaseResponse\"\x00\x12U\n\rUpdateChichat\x12\x1d.robotSkillApi.ChichatRequest\x1a#.robotSkillApi.OperatorBaseResponse\"\x00\x12V\n\x06SendFR\x12%.robotSkillApi.FaceRecognitionRequest\x1a#.robotSkillApi.OperatorBaseResponse\"\x00\x42>Z<cloudminds.com/harix/harix-skill-robot/proto/robot-skill-apib\x06proto3')
  ,
  dependencies=[common_dot_common__pb2.DESCRIPTOR,])




_SWITCHREQUEST = _descriptor.Descriptor(
  name='SwitchRequest',
  full_name='robotSkillApi.SwitchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='common_req_info', full_name='robotSkillApi.SwitchRequest.common_req_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='confidence_index', full_name='robotSkillApi.SwitchRequest.confidence_index', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reason', full_name='robotSkillApi.SwitchRequest.reason', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=185,
)


_CONFIDENCEREQUEST = _descriptor.Descriptor(
  name='ConfidenceRequest',
  full_name='robotSkillApi.ConfidenceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='common_req_info', full_name='robotSkillApi.ConfidenceRequest.common_req_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='confidence_index', full_name='robotSkillApi.ConfidenceRequest.confidence_index', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=280,
)


_OPERATORBASERESPONSE = _descriptor.Descriptor(
  name='OperatorBaseResponse',
  full_name='robotSkillApi.OperatorBaseResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='common_rsp_info', full_name='robotSkillApi.OperatorBaseResponse.common_rsp_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result', full_name='robotSkillApi.OperatorBaseResponse.result', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=282,
  serialized_end=368,
)


_CHICHATREQUEST = _descriptor.Descriptor(
  name='ChichatRequest',
  full_name='robotSkillApi.ChichatRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='common_req_info', full_name='robotSkillApi.ChichatRequest.common_req_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chichat', full_name='robotSkillApi.ChichatRequest.chichat', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=370,
  serialized_end=451,
)


_FACERECOGNITIONREQUEST = _descriptor.Descriptor(
  name='FaceRecognitionRequest',
  full_name='robotSkillApi.FaceRecognitionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='common_req_info', full_name='robotSkillApi.FaceRecognitionRequest.common_req_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='body', full_name='robotSkillApi.FaceRecognitionRequest.body', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=453,
  serialized_end=539,
)

_SWITCHREQUEST.fields_by_name['common_req_info'].message_type = common_dot_common__pb2._COMMONREQINFO
_CONFIDENCEREQUEST.fields_by_name['common_req_info'].message_type = common_dot_common__pb2._COMMONREQINFO
_OPERATORBASERESPONSE.fields_by_name['common_rsp_info'].message_type = common_dot_common__pb2._COMMONRSPINFO
_CHICHATREQUEST.fields_by_name['common_req_info'].message_type = common_dot_common__pb2._COMMONREQINFO
_FACERECOGNITIONREQUEST.fields_by_name['common_req_info'].message_type = common_dot_common__pb2._COMMONREQINFO
DESCRIPTOR.message_types_by_name['SwitchRequest'] = _SWITCHREQUEST
DESCRIPTOR.message_types_by_name['ConfidenceRequest'] = _CONFIDENCEREQUEST
DESCRIPTOR.message_types_by_name['OperatorBaseResponse'] = _OPERATORBASERESPONSE
DESCRIPTOR.message_types_by_name['ChichatRequest'] = _CHICHATREQUEST
DESCRIPTOR.message_types_by_name['FaceRecognitionRequest'] = _FACERECOGNITIONREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SwitchRequest = _reflection.GeneratedProtocolMessageType('SwitchRequest', (_message.Message,), {
  'DESCRIPTOR' : _SWITCHREQUEST,
  '__module__' : 'robot_skill_api.robot_operator_api_pb2'
  # @@protoc_insertion_point(class_scope:robotSkillApi.SwitchRequest)
  })
_sym_db.RegisterMessage(SwitchRequest)

ConfidenceRequest = _reflection.GeneratedProtocolMessageType('ConfidenceRequest', (_message.Message,), {
  'DESCRIPTOR' : _CONFIDENCEREQUEST,
  '__module__' : 'robot_skill_api.robot_operator_api_pb2'
  # @@protoc_insertion_point(class_scope:robotSkillApi.ConfidenceRequest)
  })
_sym_db.RegisterMessage(ConfidenceRequest)

OperatorBaseResponse = _reflection.GeneratedProtocolMessageType('OperatorBaseResponse', (_message.Message,), {
  'DESCRIPTOR' : _OPERATORBASERESPONSE,
  '__module__' : 'robot_skill_api.robot_operator_api_pb2'
  # @@protoc_insertion_point(class_scope:robotSkillApi.OperatorBaseResponse)
  })
_sym_db.RegisterMessage(OperatorBaseResponse)

ChichatRequest = _reflection.GeneratedProtocolMessageType('ChichatRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHICHATREQUEST,
  '__module__' : 'robot_skill_api.robot_operator_api_pb2'
  # @@protoc_insertion_point(class_scope:robotSkillApi.ChichatRequest)
  })
_sym_db.RegisterMessage(ChichatRequest)

FaceRecognitionRequest = _reflection.GeneratedProtocolMessageType('FaceRecognitionRequest', (_message.Message,), {
  'DESCRIPTOR' : _FACERECOGNITIONREQUEST,
  '__module__' : 'robot_skill_api.robot_operator_api_pb2'
  # @@protoc_insertion_point(class_scope:robotSkillApi.FaceRecognitionRequest)
  })
_sym_db.RegisterMessage(FaceRecognitionRequest)


DESCRIPTOR._options = None

_ROBOTOPERATORSERVICE = _descriptor.ServiceDescriptor(
  name='RobotOperatorService',
  full_name='robotSkillApi.RobotOperatorService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=542,
  serialized_end=918,
  methods=[
  _descriptor.MethodDescriptor(
    name='SwitchHi',
    full_name='robotSkillApi.RobotOperatorService.SwitchHi',
    index=0,
    containing_service=None,
    input_type=_SWITCHREQUEST,
    output_type=_OPERATORBASERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateConfidenceIndex',
    full_name='robotSkillApi.RobotOperatorService.UpdateConfidenceIndex',
    index=1,
    containing_service=None,
    input_type=_CONFIDENCEREQUEST,
    output_type=_OPERATORBASERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateChichat',
    full_name='robotSkillApi.RobotOperatorService.UpdateChichat',
    index=2,
    containing_service=None,
    input_type=_CHICHATREQUEST,
    output_type=_OPERATORBASERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendFR',
    full_name='robotSkillApi.RobotOperatorService.SendFR',
    index=3,
    containing_service=None,
    input_type=_FACERECOGNITIONREQUEST,
    output_type=_OPERATORBASERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ROBOTOPERATORSERVICE)

DESCRIPTOR.services_by_name['RobotOperatorService'] = _ROBOTOPERATORSERVICE

# @@protoc_insertion_point(module_scope)
