# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from protopb.vision import vision_pb2 as vision_dot_vision__pb2


class VisionStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Recognize = channel.unary_unary(
        '/skill.vision.Vision/Recognize',
        request_serializer=vision_dot_vision__pb2.ImageRequest.SerializeToString,
        response_deserializer=vision_dot_vision__pb2.ImageResponse.FromString,
        )
    self.StreamingRecognize = channel.stream_unary(
        '/skill.vision.Vision/StreamingRecognize',
        request_serializer=vision_dot_vision__pb2.ImageRequest.SerializeToString,
        response_deserializer=vision_dot_vision__pb2.ImageResponse.FromString,
        )


class VisionServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Recognize(self, request, context):
    """sync call for result, use by service-app usually
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StreamingRecognize(self, request_iterator, context):
    """sync call , use by rcu or other end point
    receive multi-face or other
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_VisionServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Recognize': grpc.unary_unary_rpc_method_handler(
          servicer.Recognize,
          request_deserializer=vision_dot_vision__pb2.ImageRequest.FromString,
          response_serializer=vision_dot_vision__pb2.ImageResponse.SerializeToString,
      ),
      'StreamingRecognize': grpc.stream_unary_rpc_method_handler(
          servicer.StreamingRecognize,
          request_deserializer=vision_dot_vision__pb2.ImageRequest.FromString,
          response_serializer=vision_dot_vision__pb2.ImageResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'skill.vision.Vision', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
