# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: serviceapp/recognizeSpeech.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protopb.common import common_pb2 as common_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='serviceapp/recognizeSpeech.proto',
  package='serviceapp',
  syntax='proto3',
  serialized_options=_b('\n%com.cloudminds.harix.skill.serviceappB\024RecognizeSpeechProtoP\001\242\002\007Service'),
  serialized_pb=_b('\n serviceapp/recognizeSpeech.proto\x12\nserviceapp\x1a\x13\x63ommon/common.proto\"\xcc\x02\n\x11RecognitionResult\x12.\n\x0f\x63ommon_req_info\x18\x01 \x01(\x0b\x32\x15.common.CommonReqInfo\x12\x30\n\x04\x62ody\x18\x02 \x01(\x0b\x32\".serviceapp.RecognitionResult.Body\x12\x1c\n\x05\x65xtra\x18\x03 \x01(\x0b\x32\r.common.Extra\x1a[\n\x04\x42ody\x12\x0c\n\x04\x66lag\x18\x01 \x01(\x05\x12\x0b\n\x03sid\x18\x02 \x01(\t\x12\x38\n\x08question\x18\x03 \x01(\x0b\x32&.serviceapp.RecognitionResult.Question\x1aZ\n\x08Question\x12\x13\n\x0bquestion_id\x18\x01 \x01(\t\x12\x0c\n\x04lang\x18\x02 \x01(\t\x12\r\n\x05\x61udio\x18\x03 \x01(\t\x12\x0c\n\x04text\x18\x04 \x01(\t\x12\x0e\n\x06qaFlag\x18\x05 \x01(\t\"E\n\x13RecognitionResponse\x12.\n\x0f\x63ommon_rsp_info\x18\x01 \x01(\x0b\x32\x15.common.CommonRspInfo2_\n\x06Speech\x12U\n\x11OnRecognizeResult\x12\x1d.serviceapp.RecognitionResult\x1a\x1f.serviceapp.RecognitionResponse\"\x00\x42I\n%com.cloudminds.harix.skill.serviceappB\x14RecognizeSpeechProtoP\x01\xa2\x02\x07Serviceb\x06proto3')
  ,
  dependencies=[common_dot_common__pb2.DESCRIPTOR,])




_RECOGNITIONRESULT_BODY = _descriptor.Descriptor(
  name='Body',
  full_name='serviceapp.RecognitionResult.Body',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='flag', full_name='serviceapp.RecognitionResult.Body.flag', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sid', full_name='serviceapp.RecognitionResult.Body.sid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='question', full_name='serviceapp.RecognitionResult.Body.question', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=310,
)

_RECOGNITIONRESULT_QUESTION = _descriptor.Descriptor(
  name='Question',
  full_name='serviceapp.RecognitionResult.Question',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='question_id', full_name='serviceapp.RecognitionResult.Question.question_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lang', full_name='serviceapp.RecognitionResult.Question.lang', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='audio', full_name='serviceapp.RecognitionResult.Question.audio', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='serviceapp.RecognitionResult.Question.text', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='qaFlag', full_name='serviceapp.RecognitionResult.Question.qaFlag', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=312,
  serialized_end=402,
)

_RECOGNITIONRESULT = _descriptor.Descriptor(
  name='RecognitionResult',
  full_name='serviceapp.RecognitionResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='common_req_info', full_name='serviceapp.RecognitionResult.common_req_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='body', full_name='serviceapp.RecognitionResult.body', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='extra', full_name='serviceapp.RecognitionResult.extra', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_RECOGNITIONRESULT_BODY, _RECOGNITIONRESULT_QUESTION, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=402,
)


_RECOGNITIONRESPONSE = _descriptor.Descriptor(
  name='RecognitionResponse',
  full_name='serviceapp.RecognitionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='common_rsp_info', full_name='serviceapp.RecognitionResponse.common_rsp_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=404,
  serialized_end=473,
)

_RECOGNITIONRESULT_BODY.fields_by_name['question'].message_type = _RECOGNITIONRESULT_QUESTION
_RECOGNITIONRESULT_BODY.containing_type = _RECOGNITIONRESULT
_RECOGNITIONRESULT_QUESTION.containing_type = _RECOGNITIONRESULT
_RECOGNITIONRESULT.fields_by_name['common_req_info'].message_type = common_dot_common__pb2._COMMONREQINFO
_RECOGNITIONRESULT.fields_by_name['body'].message_type = _RECOGNITIONRESULT_BODY
_RECOGNITIONRESULT.fields_by_name['extra'].message_type = common_dot_common__pb2._EXTRA
_RECOGNITIONRESPONSE.fields_by_name['common_rsp_info'].message_type = common_dot_common__pb2._COMMONRSPINFO
DESCRIPTOR.message_types_by_name['RecognitionResult'] = _RECOGNITIONRESULT
DESCRIPTOR.message_types_by_name['RecognitionResponse'] = _RECOGNITIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RecognitionResult = _reflection.GeneratedProtocolMessageType('RecognitionResult', (_message.Message,), {

  'Body' : _reflection.GeneratedProtocolMessageType('Body', (_message.Message,), {
    'DESCRIPTOR' : _RECOGNITIONRESULT_BODY,
    '__module__' : 'serviceapp.recognizeSpeech_pb2'
    # @@protoc_insertion_point(class_scope:serviceapp.RecognitionResult.Body)
    })
  ,

  'Question' : _reflection.GeneratedProtocolMessageType('Question', (_message.Message,), {
    'DESCRIPTOR' : _RECOGNITIONRESULT_QUESTION,
    '__module__' : 'serviceapp.recognizeSpeech_pb2'
    # @@protoc_insertion_point(class_scope:serviceapp.RecognitionResult.Question)
    })
  ,
  'DESCRIPTOR' : _RECOGNITIONRESULT,
  '__module__' : 'serviceapp.recognizeSpeech_pb2'
  # @@protoc_insertion_point(class_scope:serviceapp.RecognitionResult)
  })
_sym_db.RegisterMessage(RecognitionResult)
_sym_db.RegisterMessage(RecognitionResult.Body)
_sym_db.RegisterMessage(RecognitionResult.Question)

RecognitionResponse = _reflection.GeneratedProtocolMessageType('RecognitionResponse', (_message.Message,), {
  'DESCRIPTOR' : _RECOGNITIONRESPONSE,
  '__module__' : 'serviceapp.recognizeSpeech_pb2'
  # @@protoc_insertion_point(class_scope:serviceapp.RecognitionResponse)
  })
_sym_db.RegisterMessage(RecognitionResponse)


DESCRIPTOR._options = None

_SPEECH = _descriptor.ServiceDescriptor(
  name='Speech',
  full_name='serviceapp.Speech',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=475,
  serialized_end=570,
  methods=[
  _descriptor.MethodDescriptor(
    name='OnRecognizeResult',
    full_name='serviceapp.Speech.OnRecognizeResult',
    index=0,
    containing_service=None,
    input_type=_RECOGNITIONRESULT,
    output_type=_RECOGNITIONRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SPEECH)

DESCRIPTOR.services_by_name['Speech'] = _SPEECH

# @@protoc_insertion_point(module_scope)
