# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from protopb.robot_skill_api import robot_navigate_api_pb2 as robot__skill__api_dot_robot__navigate__api__pb2


class RobotNavigateServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetRobotMapList = channel.unary_unary(
        '/robotSkillApi.RobotNavigateService/GetRobotMapList',
        request_serializer=robot__skill__api_dot_robot__navigate__api__pb2.MapRequest.SerializeToString,
        response_deserializer=robot__skill__api_dot_robot__navigate__api__pb2.NavigateBaseResponse.FromString,
        )
    self.GetMapLocation = channel.unary_unary(
        '/robotSkillApi.RobotNavigateService/GetMapLocation',
        request_serializer=robot__skill__api_dot_robot__navigate__api__pb2.MapRequest.SerializeToString,
        response_deserializer=robot__skill__api_dot_robot__navigate__api__pb2.NavigateBaseResponse.FromString,
        )
    self.GetPatrolRoute = channel.unary_unary(
        '/robotSkillApi.RobotNavigateService/GetPatrolRoute',
        request_serializer=robot__skill__api_dot_robot__navigate__api__pb2.GetPatrolRequest.SerializeToString,
        response_deserializer=robot__skill__api_dot_robot__navigate__api__pb2.NavigateBaseResponse.FromString,
        )
    self.DeleteRobotMap = channel.unary_unary(
        '/robotSkillApi.RobotNavigateService/DeleteRobotMap',
        request_serializer=robot__skill__api_dot_robot__navigate__api__pb2.MapRequest.SerializeToString,
        response_deserializer=robot__skill__api_dot_robot__navigate__api__pb2.NavigateBaseResponse.FromString,
        )
    self.setActiveMap = channel.unary_unary(
        '/robotSkillApi.RobotNavigateService/setActiveMap',
        request_serializer=robot__skill__api_dot_robot__navigate__api__pb2.MapRequest.SerializeToString,
        response_deserializer=robot__skill__api_dot_robot__navigate__api__pb2.NavigateBaseResponse.FromString,
        )
    self.NotifyMapUpdated = channel.unary_unary(
        '/robotSkillApi.RobotNavigateService/NotifyMapUpdated',
        request_serializer=robot__skill__api_dot_robot__navigate__api__pb2.MapRequest.SerializeToString,
        response_deserializer=robot__skill__api_dot_robot__navigate__api__pb2.NavigateBaseResponse.FromString,
        )
    self.StartPatrol = channel.unary_unary(
        '/robotSkillApi.RobotNavigateService/StartPatrol',
        request_serializer=robot__skill__api_dot_robot__navigate__api__pb2.PatrolRequest.SerializeToString,
        response_deserializer=robot__skill__api_dot_robot__navigate__api__pb2.NavigateBaseResponse.FromString,
        )
    self.PausePatrol = channel.unary_unary(
        '/robotSkillApi.RobotNavigateService/PausePatrol',
        request_serializer=robot__skill__api_dot_robot__navigate__api__pb2.PatrolRequest.SerializeToString,
        response_deserializer=robot__skill__api_dot_robot__navigate__api__pb2.NavigateBaseResponse.FromString,
        )
    self.ResumePatrol = channel.unary_unary(
        '/robotSkillApi.RobotNavigateService/ResumePatrol',
        request_serializer=robot__skill__api_dot_robot__navigate__api__pb2.PatrolRequest.SerializeToString,
        response_deserializer=robot__skill__api_dot_robot__navigate__api__pb2.NavigateBaseResponse.FromString,
        )
    self.StopPatrol = channel.unary_unary(
        '/robotSkillApi.RobotNavigateService/StopPatrol',
        request_serializer=robot__skill__api_dot_robot__navigate__api__pb2.PatrolRequest.SerializeToString,
        response_deserializer=robot__skill__api_dot_robot__navigate__api__pb2.NavigateBaseResponse.FromString,
        )
    self.EnableCalibrationPoints = channel.unary_unary(
        '/robotSkillApi.RobotNavigateService/EnableCalibrationPoints',
        request_serializer=robot__skill__api_dot_robot__navigate__api__pb2.EnableCalibrationPointsRequest.SerializeToString,
        response_deserializer=robot__skill__api_dot_robot__navigate__api__pb2.NavigateBaseResponse.FromString,
        )
    self.MoveTo = channel.unary_unary(
        '/robotSkillApi.RobotNavigateService/MoveTo',
        request_serializer=robot__skill__api_dot_robot__navigate__api__pb2.MoveToRequest.SerializeToString,
        response_deserializer=robot__skill__api_dot_robot__navigate__api__pb2.NavigateBaseResponse.FromString,
        )
    self.MoveByPath = channel.unary_unary(
        '/robotSkillApi.RobotNavigateService/MoveByPath',
        request_serializer=robot__skill__api_dot_robot__navigate__api__pb2.MoveByPathRequest.SerializeToString,
        response_deserializer=robot__skill__api_dot_robot__navigate__api__pb2.NavigateBaseResponse.FromString,
        )
    self.SetRobotLocation = channel.unary_unary(
        '/robotSkillApi.RobotNavigateService/SetRobotLocation',
        request_serializer=robot__skill__api_dot_robot__navigate__api__pb2.SetRobotLocationRequest.SerializeToString,
        response_deserializer=robot__skill__api_dot_robot__navigate__api__pb2.NavigateBaseResponse.FromString,
        )
    self.SetDefaultChargingSite = channel.unary_unary(
        '/robotSkillApi.RobotNavigateService/SetDefaultChargingSite',
        request_serializer=robot__skill__api_dot_robot__navigate__api__pb2.ChargingSiteRequest.SerializeToString,
        response_deserializer=robot__skill__api_dot_robot__navigate__api__pb2.NavigateBaseResponse.FromString,
        )
    self.AttachChargingPile = channel.unary_unary(
        '/robotSkillApi.RobotNavigateService/AttachChargingPile',
        request_serializer=robot__skill__api_dot_robot__navigate__api__pb2.ChargingSiteRequest.SerializeToString,
        response_deserializer=robot__skill__api_dot_robot__navigate__api__pb2.NavigateBaseResponse.FromString,
        )
    self.DetachChargingPile = channel.unary_unary(
        '/robotSkillApi.RobotNavigateService/DetachChargingPile',
        request_serializer=robot__skill__api_dot_robot__navigate__api__pb2.ChargingSiteRequest.SerializeToString,
        response_deserializer=robot__skill__api_dot_robot__navigate__api__pb2.NavigateBaseResponse.FromString,
        )


class RobotNavigateServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetRobotMapList(self, request, context):
    """获取机器人地图信息
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMapLocation(self, request, context):
    """获取地图上预先定义的兴趣点
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPatrolRoute(self, request, context):
    """获取巡逻路径信息
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteRobotMap(self, request, context):
    """删除机器人的地图
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def setActiveMap(self, request, context):
    """设置机器人当前使用的地图
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def NotifyMapUpdated(self, request, context):
    """通知机器人地图状态的改变
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StartPatrol(self, request, context):
    """启动巡逻
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PausePatrol(self, request, context):
    """暂停巡逻
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ResumePatrol(self, request, context):
    """恢复巡逻
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StopPatrol(self, request, context):
    """停止巡逻
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EnableCalibrationPoints(self, request, context):
    """校准点上传
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def MoveTo(self, request, context):
    """移动到
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def MoveByPath(self, request, context):
    """移动一段路径
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetRobotLocation(self, request, context):
    """设置机器人位置
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetDefaultChargingSite(self, request, context):
    """设置默认充电桩位置
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AttachChargingPile(self, request, context):
    """充电
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DetachChargingPile(self, request, context):
    """取消充电
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RobotNavigateServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetRobotMapList': grpc.unary_unary_rpc_method_handler(
          servicer.GetRobotMapList,
          request_deserializer=robot__skill__api_dot_robot__navigate__api__pb2.MapRequest.FromString,
          response_serializer=robot__skill__api_dot_robot__navigate__api__pb2.NavigateBaseResponse.SerializeToString,
      ),
      'GetMapLocation': grpc.unary_unary_rpc_method_handler(
          servicer.GetMapLocation,
          request_deserializer=robot__skill__api_dot_robot__navigate__api__pb2.MapRequest.FromString,
          response_serializer=robot__skill__api_dot_robot__navigate__api__pb2.NavigateBaseResponse.SerializeToString,
      ),
      'GetPatrolRoute': grpc.unary_unary_rpc_method_handler(
          servicer.GetPatrolRoute,
          request_deserializer=robot__skill__api_dot_robot__navigate__api__pb2.GetPatrolRequest.FromString,
          response_serializer=robot__skill__api_dot_robot__navigate__api__pb2.NavigateBaseResponse.SerializeToString,
      ),
      'DeleteRobotMap': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteRobotMap,
          request_deserializer=robot__skill__api_dot_robot__navigate__api__pb2.MapRequest.FromString,
          response_serializer=robot__skill__api_dot_robot__navigate__api__pb2.NavigateBaseResponse.SerializeToString,
      ),
      'setActiveMap': grpc.unary_unary_rpc_method_handler(
          servicer.setActiveMap,
          request_deserializer=robot__skill__api_dot_robot__navigate__api__pb2.MapRequest.FromString,
          response_serializer=robot__skill__api_dot_robot__navigate__api__pb2.NavigateBaseResponse.SerializeToString,
      ),
      'NotifyMapUpdated': grpc.unary_unary_rpc_method_handler(
          servicer.NotifyMapUpdated,
          request_deserializer=robot__skill__api_dot_robot__navigate__api__pb2.MapRequest.FromString,
          response_serializer=robot__skill__api_dot_robot__navigate__api__pb2.NavigateBaseResponse.SerializeToString,
      ),
      'StartPatrol': grpc.unary_unary_rpc_method_handler(
          servicer.StartPatrol,
          request_deserializer=robot__skill__api_dot_robot__navigate__api__pb2.PatrolRequest.FromString,
          response_serializer=robot__skill__api_dot_robot__navigate__api__pb2.NavigateBaseResponse.SerializeToString,
      ),
      'PausePatrol': grpc.unary_unary_rpc_method_handler(
          servicer.PausePatrol,
          request_deserializer=robot__skill__api_dot_robot__navigate__api__pb2.PatrolRequest.FromString,
          response_serializer=robot__skill__api_dot_robot__navigate__api__pb2.NavigateBaseResponse.SerializeToString,
      ),
      'ResumePatrol': grpc.unary_unary_rpc_method_handler(
          servicer.ResumePatrol,
          request_deserializer=robot__skill__api_dot_robot__navigate__api__pb2.PatrolRequest.FromString,
          response_serializer=robot__skill__api_dot_robot__navigate__api__pb2.NavigateBaseResponse.SerializeToString,
      ),
      'StopPatrol': grpc.unary_unary_rpc_method_handler(
          servicer.StopPatrol,
          request_deserializer=robot__skill__api_dot_robot__navigate__api__pb2.PatrolRequest.FromString,
          response_serializer=robot__skill__api_dot_robot__navigate__api__pb2.NavigateBaseResponse.SerializeToString,
      ),
      'EnableCalibrationPoints': grpc.unary_unary_rpc_method_handler(
          servicer.EnableCalibrationPoints,
          request_deserializer=robot__skill__api_dot_robot__navigate__api__pb2.EnableCalibrationPointsRequest.FromString,
          response_serializer=robot__skill__api_dot_robot__navigate__api__pb2.NavigateBaseResponse.SerializeToString,
      ),
      'MoveTo': grpc.unary_unary_rpc_method_handler(
          servicer.MoveTo,
          request_deserializer=robot__skill__api_dot_robot__navigate__api__pb2.MoveToRequest.FromString,
          response_serializer=robot__skill__api_dot_robot__navigate__api__pb2.NavigateBaseResponse.SerializeToString,
      ),
      'MoveByPath': grpc.unary_unary_rpc_method_handler(
          servicer.MoveByPath,
          request_deserializer=robot__skill__api_dot_robot__navigate__api__pb2.MoveByPathRequest.FromString,
          response_serializer=robot__skill__api_dot_robot__navigate__api__pb2.NavigateBaseResponse.SerializeToString,
      ),
      'SetRobotLocation': grpc.unary_unary_rpc_method_handler(
          servicer.SetRobotLocation,
          request_deserializer=robot__skill__api_dot_robot__navigate__api__pb2.SetRobotLocationRequest.FromString,
          response_serializer=robot__skill__api_dot_robot__navigate__api__pb2.NavigateBaseResponse.SerializeToString,
      ),
      'SetDefaultChargingSite': grpc.unary_unary_rpc_method_handler(
          servicer.SetDefaultChargingSite,
          request_deserializer=robot__skill__api_dot_robot__navigate__api__pb2.ChargingSiteRequest.FromString,
          response_serializer=robot__skill__api_dot_robot__navigate__api__pb2.NavigateBaseResponse.SerializeToString,
      ),
      'AttachChargingPile': grpc.unary_unary_rpc_method_handler(
          servicer.AttachChargingPile,
          request_deserializer=robot__skill__api_dot_robot__navigate__api__pb2.ChargingSiteRequest.FromString,
          response_serializer=robot__skill__api_dot_robot__navigate__api__pb2.NavigateBaseResponse.SerializeToString,
      ),
      'DetachChargingPile': grpc.unary_unary_rpc_method_handler(
          servicer.DetachChargingPile,
          request_deserializer=robot__skill__api_dot_robot__navigate__api__pb2.ChargingSiteRequest.FromString,
          response_serializer=robot__skill__api_dot_robot__navigate__api__pb2.NavigateBaseResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'robotSkillApi.RobotNavigateService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
