# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: speech/speech.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protopb.common import common_pb2 as common_dot_common__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='speech/speech.proto',
  package='skill.asr',
  syntax='proto3',
  serialized_options=_b('\n\036com.cloudminds.harix.skill.asrB\013SpeechProtoP\001\242\002\003ASR'),
  serialized_pb=_b('\n\x13speech/speech.proto\x12\tskill.asr\x1a\x13\x63ommon/common.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xb9\x03\n\x04\x42ody\x12\"\n\x04type\x18\t \x01(\x0e\x32\x14.skill.asr.Body.Type\x12\x0b\n\x03sid\x18\n \x01(\t\x12\x10\n\x08\x61pp_type\x18\x0b \x01(\t\x12\x0b\n\x03tag\x18\x0c \x01(\t\x12\x13\n\x0bstream_flag\x18\r \x01(\x05\x12+\n\x06option\x18\x0e \x03(\x0b\x32\x1b.skill.asr.Body.OptionEntry\x12\"\n\x04\x64\x61ta\x18\x0f \x01(\x0b\x32\x14.skill.asr.Body.Data\x1a-\n\x0bOptionEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\xa9\x01\n\x04\x44\x61ta\x12\x0c\n\x04rate\x18\x01 \x01(\x05\x12\x0e\n\x06\x66ormat\x18\x02 \x01(\t\x12\x0f\n\x07\x61\x63\x63ount\x18\x03 \x01(\t\x12\x10\n\x08language\x18\x04 \x01(\t\x12\x0f\n\x07\x64ialect\x18\x05 \x01(\t\x12\x0e\n\x06vendor\x18\x06 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x07 \x01(\x05\x12\x10\n\x08\x64uration\x18\x08 \x01(\x05\x12\x0c\n\x04\x66lag\x18\t \x01(\x05\x12\x0e\n\x06speech\x18\n \x01(\x0c\" \n\x04Type\x12\t\n\x05\x42LOCK\x10\x00\x12\r\n\tSTREAMING\x10\x01\"\x81\x01\n\x12RecognitionRequest\x12.\n\x0f\x63ommon_req_info\x18\x01 \x01(\x0b\x32\x15.common.CommonReqInfo\x12\x1d\n\x04\x62ody\x18\x02 \x01(\x0b\x32\x0f.skill.asr.Body\x12\x1c\n\x05\x65xtra\x18\x03 \x01(\x0b\x32\r.common.Extra\"\x9d\x01\n\x13RecognitionResponse\x12.\n\x0f\x63ommon_rsp_info\x18\x01 \x01(\x0b\x32\x15.common.CommonRspInfo\x12/\n\x0e\x64\x65tail_message\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x10\n\x08is_noise\x18\x03 \x01(\x08\x12\x13\n\x0bquestion_id\x18\x04 \x01(\t2\xb1\x01\n\x06Speech\x12L\n\tRecognize\x12\x1d.skill.asr.RecognitionRequest\x1a\x1e.skill.asr.RecognitionResponse\"\x00\x12Y\n\x12StreamingRecognize\x12\x1d.skill.asr.RecognitionRequest\x1a\x1e.skill.asr.RecognitionResponse\"\x00(\x01\x30\x01\x42\x35\n\x1e\x63om.cloudminds.harix.skill.asrB\x0bSpeechProtoP\x01\xa2\x02\x03\x41SRb\x06proto3')
  ,
  dependencies=[common_dot_common__pb2.DESCRIPTOR,google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])



_BODY_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='skill.asr.Body.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BLOCK', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STREAMING', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=495,
  serialized_end=527,
)
_sym_db.RegisterEnumDescriptor(_BODY_TYPE)


_BODY_OPTIONENTRY = _descriptor.Descriptor(
  name='OptionEntry',
  full_name='skill.asr.Body.OptionEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='skill.asr.Body.OptionEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='skill.asr.Body.OptionEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=276,
  serialized_end=321,
)

_BODY_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='skill.asr.Body.Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rate', full_name='skill.asr.Body.Data.rate', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='format', full_name='skill.asr.Body.Data.format', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='account', full_name='skill.asr.Body.Data.account', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='language', full_name='skill.asr.Body.Data.language', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dialect', full_name='skill.asr.Body.Data.dialect', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vendor', full_name='skill.asr.Body.Data.vendor', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='channel', full_name='skill.asr.Body.Data.channel', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='duration', full_name='skill.asr.Body.Data.duration', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flag', full_name='skill.asr.Body.Data.flag', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='speech', full_name='skill.asr.Body.Data.speech', index=9,
      number=10, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=324,
  serialized_end=493,
)

_BODY = _descriptor.Descriptor(
  name='Body',
  full_name='skill.asr.Body',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='skill.asr.Body.type', index=0,
      number=9, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sid', full_name='skill.asr.Body.sid', index=1,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='app_type', full_name='skill.asr.Body.app_type', index=2,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tag', full_name='skill.asr.Body.tag', index=3,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stream_flag', full_name='skill.asr.Body.stream_flag', index=4,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='option', full_name='skill.asr.Body.option', index=5,
      number=14, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='skill.asr.Body.data', index=6,
      number=15, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_BODY_OPTIONENTRY, _BODY_DATA, ],
  enum_types=[
    _BODY_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=527,
)


_RECOGNITIONREQUEST = _descriptor.Descriptor(
  name='RecognitionRequest',
  full_name='skill.asr.RecognitionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='common_req_info', full_name='skill.asr.RecognitionRequest.common_req_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='body', full_name='skill.asr.RecognitionRequest.body', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='extra', full_name='skill.asr.RecognitionRequest.extra', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=530,
  serialized_end=659,
)


_RECOGNITIONRESPONSE = _descriptor.Descriptor(
  name='RecognitionResponse',
  full_name='skill.asr.RecognitionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='common_rsp_info', full_name='skill.asr.RecognitionResponse.common_rsp_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='detail_message', full_name='skill.asr.RecognitionResponse.detail_message', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_noise', full_name='skill.asr.RecognitionResponse.is_noise', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='question_id', full_name='skill.asr.RecognitionResponse.question_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=662,
  serialized_end=819,
)

_BODY_OPTIONENTRY.containing_type = _BODY
_BODY_DATA.containing_type = _BODY
_BODY.fields_by_name['type'].enum_type = _BODY_TYPE
_BODY.fields_by_name['option'].message_type = _BODY_OPTIONENTRY
_BODY.fields_by_name['data'].message_type = _BODY_DATA
_BODY_TYPE.containing_type = _BODY
_RECOGNITIONREQUEST.fields_by_name['common_req_info'].message_type = common_dot_common__pb2._COMMONREQINFO
_RECOGNITIONREQUEST.fields_by_name['body'].message_type = _BODY
_RECOGNITIONREQUEST.fields_by_name['extra'].message_type = common_dot_common__pb2._EXTRA
_RECOGNITIONRESPONSE.fields_by_name['common_rsp_info'].message_type = common_dot_common__pb2._COMMONRSPINFO
_RECOGNITIONRESPONSE.fields_by_name['detail_message'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
DESCRIPTOR.message_types_by_name['Body'] = _BODY
DESCRIPTOR.message_types_by_name['RecognitionRequest'] = _RECOGNITIONREQUEST
DESCRIPTOR.message_types_by_name['RecognitionResponse'] = _RECOGNITIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Body = _reflection.GeneratedProtocolMessageType('Body', (_message.Message,), {

  'OptionEntry' : _reflection.GeneratedProtocolMessageType('OptionEntry', (_message.Message,), {
    'DESCRIPTOR' : _BODY_OPTIONENTRY,
    '__module__' : 'speech.speech_pb2'
    # @@protoc_insertion_point(class_scope:skill.asr.Body.OptionEntry)
    })
  ,

  'Data' : _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), {
    'DESCRIPTOR' : _BODY_DATA,
    '__module__' : 'speech.speech_pb2'
    # @@protoc_insertion_point(class_scope:skill.asr.Body.Data)
    })
  ,
  'DESCRIPTOR' : _BODY,
  '__module__' : 'speech.speech_pb2'
  # @@protoc_insertion_point(class_scope:skill.asr.Body)
  })
_sym_db.RegisterMessage(Body)
_sym_db.RegisterMessage(Body.OptionEntry)
_sym_db.RegisterMessage(Body.Data)

RecognitionRequest = _reflection.GeneratedProtocolMessageType('RecognitionRequest', (_message.Message,), {
  'DESCRIPTOR' : _RECOGNITIONREQUEST,
  '__module__' : 'speech.speech_pb2'
  # @@protoc_insertion_point(class_scope:skill.asr.RecognitionRequest)
  })
_sym_db.RegisterMessage(RecognitionRequest)

RecognitionResponse = _reflection.GeneratedProtocolMessageType('RecognitionResponse', (_message.Message,), {
  'DESCRIPTOR' : _RECOGNITIONRESPONSE,
  '__module__' : 'speech.speech_pb2'
  # @@protoc_insertion_point(class_scope:skill.asr.RecognitionResponse)
  })
_sym_db.RegisterMessage(RecognitionResponse)


DESCRIPTOR._options = None
_BODY_OPTIONENTRY._options = None

_SPEECH = _descriptor.ServiceDescriptor(
  name='Speech',
  full_name='skill.asr.Speech',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=822,
  serialized_end=999,
  methods=[
  _descriptor.MethodDescriptor(
    name='Recognize',
    full_name='skill.asr.Speech.Recognize',
    index=0,
    containing_service=None,
    input_type=_RECOGNITIONREQUEST,
    output_type=_RECOGNITIONRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StreamingRecognize',
    full_name='skill.asr.Speech.StreamingRecognize',
    index=1,
    containing_service=None,
    input_type=_RECOGNITIONREQUEST,
    output_type=_RECOGNITIONRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SPEECH)

DESCRIPTOR.services_by_name['Speech'] = _SPEECH

# @@protoc_insertion_point(module_scope)
