# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common/common.proto',
  package='common',
  syntax='proto3',
  serialized_options=_b('\n\033com.cloudminds.harix.commonB\013CommonProtoP\001Z3cloudminds.com/harix/harix-skill-robot/proto/common\242\002\006common\252\002\007Commons'),
  serialized_pb=_b('\n\x13\x63ommon/common.proto\x12\x06\x63ommon\"\xc1\x01\n\rCommonReqInfo\x12\x0c\n\x04guid\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x11\n\ttenant_id\x18\x04 \x01(\t\x12\x0f\n\x07user_id\x18\x05 \x01(\t\x12\x10\n\x08robot_id\x18\x06 \x01(\t\x12\x12\n\nrobot_type\x18\x07 \x01(\t\x12\x14\n\x0cservice_code\x18\x08 \x01(\t\x12\x0b\n\x03seq\x18\t \x01(\t\x12\x11\n\troot_guid\x18\n \x01(\t\"F\n\rCommonRspInfo\x12\x10\n\x08\x65rr_code\x18\x01 \x01(\x05\x12\x0f\n\x07\x65rr_msg\x18\x02 \x01(\t\x12\x12\n\nerr_detail\x18\x03 \x01(\t\"/\n\x05\x45xtra\x12\x12\n\nextra_type\x18\x01 \x01(\t\x12\x12\n\nextra_body\x18\x02 \x01(\tBt\n\x1b\x63om.cloudminds.harix.commonB\x0b\x43ommonProtoP\x01Z3cloudminds.com/harix/harix-skill-robot/proto/common\xa2\x02\x06\x63ommon\xaa\x02\x07\x43ommonsb\x06proto3')
)




_COMMONREQINFO = _descriptor.Descriptor(
  name='CommonReqInfo',
  full_name='common.CommonReqInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='guid', full_name='common.CommonReqInfo.guid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='common.CommonReqInfo.timestamp', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='common.CommonReqInfo.version', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tenant_id', full_name='common.CommonReqInfo.tenant_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='common.CommonReqInfo.user_id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='robot_id', full_name='common.CommonReqInfo.robot_id', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='robot_type', full_name='common.CommonReqInfo.robot_type', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='service_code', full_name='common.CommonReqInfo.service_code', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seq', full_name='common.CommonReqInfo.seq', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='root_guid', full_name='common.CommonReqInfo.root_guid', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=225,
)


_COMMONRSPINFO = _descriptor.Descriptor(
  name='CommonRspInfo',
  full_name='common.CommonRspInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='err_code', full_name='common.CommonRspInfo.err_code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='err_msg', full_name='common.CommonRspInfo.err_msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='err_detail', full_name='common.CommonRspInfo.err_detail', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=227,
  serialized_end=297,
)


_EXTRA = _descriptor.Descriptor(
  name='Extra',
  full_name='common.Extra',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='extra_type', full_name='common.Extra.extra_type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='extra_body', full_name='common.Extra.extra_body', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=299,
  serialized_end=346,
)

DESCRIPTOR.message_types_by_name['CommonReqInfo'] = _COMMONREQINFO
DESCRIPTOR.message_types_by_name['CommonRspInfo'] = _COMMONRSPINFO
DESCRIPTOR.message_types_by_name['Extra'] = _EXTRA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CommonReqInfo = _reflection.GeneratedProtocolMessageType('CommonReqInfo', (_message.Message,), {
  'DESCRIPTOR' : _COMMONREQINFO,
  '__module__' : 'common.common_pb2'
  # @@protoc_insertion_point(class_scope:common.CommonReqInfo)
  })
_sym_db.RegisterMessage(CommonReqInfo)

CommonRspInfo = _reflection.GeneratedProtocolMessageType('CommonRspInfo', (_message.Message,), {
  'DESCRIPTOR' : _COMMONRSPINFO,
  '__module__' : 'common.common_pb2'
  # @@protoc_insertion_point(class_scope:common.CommonRspInfo)
  })
_sym_db.RegisterMessage(CommonRspInfo)

Extra = _reflection.GeneratedProtocolMessageType('Extra', (_message.Message,), {
  'DESCRIPTOR' : _EXTRA,
  '__module__' : 'common.common_pb2'
  # @@protoc_insertion_point(class_scope:common.Extra)
  })
_sym_db.RegisterMessage(Extra)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
