# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/imageType.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common/imageType.proto',
  package='common',
  syntax='proto3',
  serialized_options=_b('\n\033com.cloudminds.harix.commonB\024CommonImageTypeProtoP\001'),
  serialized_pb=_b('\n\x16\x63ommon/imageType.proto\x12\x06\x63ommon*N\n\tImageType\x12\x08\n\x04TEXT\x10\x00\x12\t\n\x05MONEY\x10\x01\x12\r\n\tCAR_PLATE\x10\x02\x12\t\n\x05IMAGE\x10\x03\x12\x08\n\x04\x46\x41\x43\x45\x10\x04\x12\x08\n\x04\x46\x41LL\x10\x05\x42\x35\n\x1b\x63om.cloudminds.harix.commonB\x14\x43ommonImageTypeProtoP\x01\x62\x06proto3')
)

_IMAGETYPE = _descriptor.EnumDescriptor(
  name='ImageType',
  full_name='common.ImageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TEXT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MONEY', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CAR_PLATE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IMAGE', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FACE', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FALL', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=34,
  serialized_end=112,
)
_sym_db.RegisterEnumDescriptor(_IMAGETYPE)

ImageType = enum_type_wrapper.EnumTypeWrapper(_IMAGETYPE)
TEXT = 0
MONEY = 1
CAR_PLATE = 2
IMAGE = 3
FACE = 4
FALL = 5


DESCRIPTOR.enum_types_by_name['ImageType'] = _IMAGETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
